import type { CSSProperties } from "react";
import {
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  Bell,
  BookOpen,
  BriefcaseBusiness,
  Camera,
  Check,
  ChevronDown,
  Clock3,
  Code2,
  Eye,
  Grid2X2,
  Heart,
  House,
  LockKeyhole,
  LogOut,
  Mail,
  MapPin,
  MessageCircle,
  Paperclip,
  PenLine,
  Plus,
  Scissors,
  Search,
  Send,
  ShieldCheck,
  Shirt,
  SlidersHorizontal,
  Sparkles,
  Star,
  Upload,
  UserRound,
  Wrench,
  X,
  type LucideIcon,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  arrow: ArrowRight,
  back: ArrowLeft,
  bell: Bell,
  book: BookOpen,
  briefcase: BriefcaseBusiness,
  camera: Camera,
  check: Check,
  chevron: ChevronDown,
  clock: Clock3,
  close: X,
  code: Code2,
  eye: Eye,
  filter: SlidersHorizontal,
  grid: Grid2X2,
  heart: Heart,
  home: House,
  lock: LockKeyhole,
  logout: LogOut,
  mail: Mail,
  message: MessageCircle,
  paperclip: Paperclip,
  pen: PenLine,
  pin: MapPin,
  plus: Plus,
  scissors: Scissors,
  search: Search,
  send: Send,
  shield: ShieldCheck,
  shirt: Shirt,
  sparkles: Sparkles,
  star: Star,
  tool: Wrench,
  upload: Upload,
  user: UserRound,
  verified: BadgeCheck,
};

export default function Icon({
  name,
  size = 20,
  style,
  className = "",
}: {
  name: string;
  size?: number;
  style?: CSSProperties;
  className?: string;
}) {
  const Component = icons[name] ?? Grid2X2;
  return <Component aria-hidden="true" className={className} size={size} style={style} strokeWidth={1.8} />;
}
