import Link from "next/link";
import {notFound} from "next/navigation";
import {Avatar} from "@/components/ui/avatar";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {getConversationById,getMessagesByConversation} from "@/data/repositories/message.repository";
import {getConversationsForUser} from "@/data/repositories/message.repository";
import {getProviderById} from "@/data/repositories/provider.repository";
import {MessageComposer} from "@/features/messaging/components/message-composer";
type Props={params:Promise<{conversationId:string}>};
export const metadata={title:"Conversation"};
export default async function Page({params}:Props){const id=(await params).conversationId;const [conversation,messages,conversations,aisha]=await Promise.all([getConversationById(id),getMessagesByConversation(id),getConversationsForUser("samuel"),getProviderById("aisha")]);if(!conversation)notFound();return <section className="content-width app-section messages-page"><div className="messages-layout"><aside className="conversation-list"><div className="conversation-list-heading"><div><strong>Messages</strong><span>{conversations.length}</span></div><Link href="/messages">View inbox</Link></div>{conversations.map(item=><Link className={`conversation-preview ${item.id===id?"selected":""}`} href={`/messages/${item.id}`} key={item.id}><Avatar src={aisha?.avatar||""} name="Aisha Bello" size={42}/><div><strong>Aisha Bello</strong><p>Quote sent · Birthday photography</p></div></Link>)}</aside><main className="conversation"><header className="conversation-header"><Avatar src={aisha?.avatar||""} name="Aisha Bello" size={44}/><div><strong>Aisha Bello</strong><span>Usually responds within 15 minutes</span></div><Badge>Student verified</Badge></header><div className="conversation-context"><div><span>Active job</span><strong>Birthday photography</strong><small>Saturday, 14 September · ₦18,000 protected</small></div><Button href="/jobs/job-birthday" variant="secondary">View job</Button></div><div className="message-history"><div className="message-date">Today</div>{messages.map(message=>message.system?<div className="system-message" key={message.id}>{message.body}</div>:<div className={`message-row ${message.senderId==="samuel"?"mine":""}`} key={message.id}><p className={`message-bubble ${message.senderId==="samuel"?"outgoing":""}`}>{message.body}</p><time>{new Date(message.createdAt).toLocaleTimeString("en-NG",{hour:"numeric",minute:"2-digit"})}</time></div>)}<MessageComposer/></div></main></div></section>}
